pipeline:
  name: myFrontEndService
  identifier: myFrontEndService
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: TestMail
          project: default_project
          inputSetReferences:
            - Email
